services:
  backend:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile

  proxy:
    image: nginx:mainline

  